### ISSUE TITLE
Replace deprecated popper library with newer floating UI library

### ISSUE THREAD

**Issue by benmccann** [themesberg/flowbite-svelte#337]
https://flowbite-svelte.com/pages/getting-started says to do `npm i -D flowbite flowbite-svelte classnames @popperjs/core`

`@popperjs/core` should no longer be used as it's deprecated. See https://floating-ui.com/docs/migration

**Comment by chris--jones** [comment]
I'd like to tackle this

**Comment by chris--jones** [comment]
It was fairly trivial to get the basics working, but because floating-ui fundamentally changes the way popups work there is a bit more refactoring to be done than I realised, There are some issues in my working environment when switching from one trigger element to another where the position is recalculated, but the placement isn't.

**Comment by denious** [comment]
Any updates?

**Comment by shinokada** [comment]
This is solved in the current version.
I close the issue for now.
Please feel free to open a new issue.
Thank you for your contribution.
