### ISSUE TITLE
add on:click attrs to components

### ISSUE THREAD

**Issue by Celestialme** [themesberg/flowbite-svelte#443]
## Summary

i want custom `on:click` event on TableBodyRow. so i can create edit modal. 

### Basic example

```
<tr {...$$restProps} class={trClassfinal} on:click>
	<slot />
</tr>
```

### Motivation
it would be ideal if flowbite has custom `on:click` handlers for  components other than buttons

**Comment by shinokada** [comment]
I'm now sure which component should have event forwarding. TableBodyCell.svelte or TableBodyRow?

**Comment by Rar9** [comment]
Currently we use a table

The row will need a on:click to do the next action of edit 

In future perhaps the cell so in line edit can be done

**Comment by shinokada** [comment]
I don't think we can add event forwarding to table row and table cell since they overwrap each other. You can create one table cell to add a link to edit page like our demo.
![image](https://user-images.githubusercontent.com/147320/204131171-4f99198d-1e62-4c37-8e05-c683bc51520e.png)

If you add a link in a cell, again it seems overwrap with a link and a click event.

**Comment by Celestialme** [comment]
why though? you can have event forwarding for everything, it does not mean user should/need to add click events on everything. it just convenience, for example if I need to add some event on some component, I am not able to. even if they overlap I can add |stoppropagation and that's it. for now I just need tablerow on:click forwarding. but in general I think you guys should support events on components like normal html elements do.
