### ISSUE TITLE
Add local transitions for components

### ISSUE THREAD

**Issue by NormandoHall** [themesberg/flowbite-svelte#533]
## Summary

Add the transition options can append `|local` param.

https://svelte.dev/docs#template-syntax-element-directives-transition-fn

### Basic example

For example, for AccordionItem:

```
<AccordionItem transitionType="slide" ...
<AccordionItem transitionType="slide|local" ...
```

or 

```
<AccordionItem transitionType="fly" ...
<AccordionItem transitionType="fly|local" ...
```

### Motivation

It is important because if it no `local` param when switching the page, there is flickering and delay the DOM update.

Also you can export `const multiple...` as `export let multiple...` ?

**Comment by 19EB** [comment]
Is there any reason not to have this as the default behavior on components like AccordionItem? 

I would imagine not having `|local` to be more of an opt-out thing.

**Comment by robertadamsonsmith** [comment]
I think this very issue even tripped up the author of the documentation.
If you go to https://flowbite-svelte.com/components/toast and then navigate to any other page, it takes 2 seconds to change properly, during which time the new page is appended to the old one. I assume this is due to the 2s transition example on that page, and the lack of |local being the default.

**Comment by NormandoHall** [comment]
Yes Robert, this is the behaviour. Please devs, make `|local` default to all transitions 🙏

**Comment by shinokada** [comment]
@jjagielka Is it possible to add `local` to the `Frame` component?

**Comment by jjagielka** [comment]
I'd be careful here. We had some problems with `local` before, when `toast` examples stopped to work.
See: https://github.com/themesberg/flowbite-svelte/pull/332#issuecomment-1272622621

**Comment by NormandoHall** [comment]
> I'd be careful here. We had some problems with `local` before, when `toast` examples stopped to work. See: [#332 (comment)](https://github.com/themesberg/flowbite-svelte/pull/332#issuecomment-1272622621)

May be better to let the developers uses `|local` or not in each component has transitions, as my previous suggestion

**Comment by robertadamsonsmith** [comment]
There is a problem with how flowbite is structured, which does not play nicely with how svelte handles local transitions.

Quoting from the svelte docs:

Local transitions only play when the block they belong to is created or destroyed, not when parent blocks are created or destroyed.
```
{#if x}
	{#if y}
		<p transition:fade>
			fades in and out when x or y change
		</p>

		<p transition:fade|local>
			fades in and out only when y changes
		</p>
	{/if}
{/if}
```
Knowing this, and looking at the Toast component (as an example), there are two problems. 

Firstly, at the root of the Toast component is an `{#if open}` block. This means that if the transition was made local, it wouldn't be fired by the Toast component itself being added/removed in the expected way from the parent element (i.e. it would require the 'open' property to be used in all cases, which effectively prevents most dynamic use cases.)

Secondly, the Toast component contains a Frame component which inserts an extra `{#if transition}` block, which ensures that a local transition could never work.

To fix this, I would firstly remove the 'open' property from the Toast component, so that we can get rid of the `{#if open}` block. It is tempting to try and encapsulate things in a component library, but if you don't do things the svelte way, then you end up fighting it.

i.e. replace this:

```
<Toast>Hello</Toast>
```

With this:
```
<script>
  let open = true;
</script>
{#if true}
  <Toast bind:open={open}>Hello</Toast>
{/if}
```
Then I would either not use the Frame component internally, or try to alter the Frame component so that the `#if transition` block can be removed. Maybe svelte:component could be used to selectively switch between a Frame component that uses transitions and one that doesn't, or a null transition with 0 duration could be used where one isn't provided (although I don't know if that would work).

Incidentally, in an ideal world it would possible to select whether a global transition was wanted instead of local, but there isn't currently a good way to do that (the local flag can't be set/unset like a regular prop, so would require some clever svelte:component hackery that would likely cause more problems than it solved). I think that a local transition is almost always the desired and expected behaviour though, so that isn't such a problem.

For the AccordianItem component, it looks like using local transitions would work fine already. I've not looked at any other components, but maybe most of the components could just have `|local` inserted at the right place, and then the more complex cases (such as Toast) could be dealt with later on.

**Comment by jjagielka** [comment]
Of course more boiler plate outside the component is a pain, and I will vote against.

The solution I see would be to change slightly the `Frame` implementation to:
```svelte
{#if transition}
  {#if open}
   <div this={tag} transition:transition|local={params} ... >
  {/if}
{/if}
```
and add the `open` prop to the `Frame`. Then in `Toast` we could simply pass `open` to the underlying `Frame`.

This is unfortunately temporary impossible due to the bug in svelte:
[Svelte #8233](https://github.com/sveltejs/svelte/issues/8233)

Once corrected, I will proceed with the proposed solution and test it out.

**Comment by NormandoHall** [comment]
@jjagielka great. Meanwhile Svelte fixes the issue, can you add the !local param only for Accordions? 🙏

**Comment by jjagielka** [comment]
PR #554 created

**Comment by shinokada** [comment]
Merged and released as v0.29.13.

**Comment by NormandoHall** [comment]
@shinokada thank you so much!!!

**Comment by NormandoHall** [comment]
Runs like a charm now! Close the issue

**Comment by shinokada** [comment]
Thank you for your contribution. Please feel free to open a new issue.
