### ISSUE TITLE
Flowbite-Svelte-Charts

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#963]
## Summary

[Flowbite charts](https://flowbite.com/docs/plugins/charts/)

Since this is a Flowbite plugin, I think it is more appropriate to create a independent repo.

- dependencies, apexcharts and flowbite-svelte
- either using svelte apexcharts wrapper lib or create own wrapper

**Comment by zoltanszogyenyi** [comment]
Hey @shinokada,

I think you could add a new "plugins" section to Flowbite Svelte instead of a separate library.

Check the docs out, we use our own `plugin` file where you can conditionally turn on or off the ApexCharts styles:

https://flowbite.com/docs/plugins/charts/

You could create a new repo if you want, but it's important to also publish it on the Flowbite Svelte documentation similar to how we built our own Charts page and examples.
